# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI

on:
  push:
    branches: [ "Stage1", "main" ]
  pull_request:
    branches: [ "Stage1", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: ./ManuProjectFiles
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./ManuProjectFiles
      run: ./gradlew build

    - name: Send email
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
      # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
      # user credentials
        username: ${{ secrets.USERNAME  }}
        password: ${{ secrets.PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: jacksonnorth1275@gmail.com,daniel.robinson.21.dr.@gmail.com
        # from email name
        from: Jackson North

  android_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        working-directory: ./ManuProjectFiles
        run: chmod +x gradlew
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          working-directory: ./ManuProjectFiles
          script: ./gradlew connectedAndroidTest
      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
        # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
        # user credentials
          username: ${{ secrets.USERNAME  }}
          password: ${{ secrets.PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: jacksonnorth1275@gmail.com,daniel.robinson.21.dr.@gmail.com
          # from email name
          from: Jackson North

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        working-directory: ./ManuProjectFiles
        run: chmod +x gradlew
      - name: Unit tests
        working-directory: ./ManuProjectFiles
        run: ./gradlew test
      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
        # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
        # user credentials
          username: ${{ secrets.USERNAME  }}
          password: ${{ secrets.PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: jacksonnorth1275@gmail.com,daniel.robinson.21.dr.@gmail.com
          # from email name
          from: Jackson North

  Generate_Docs:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Grant execute permission for gradlew
        working-directory: ./ManuProjectFiles
        run: chmod +x gradlew
      - name: Generate API documentation
        if: ${{github.event_name == 'push'}}
        working-directory: ./ManuProjectFiles
        run: ./gradlew dokkaHtml
      - name: Deploy API documentation to Github Pages
        if: ${{github.event_name == 'push'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #BRANCH: Stage1
          publish_dir: ./app/build/dokka/html # specify the 
        # builds zip file with kdoc website inside
      - name: Archive KDoc Documentation
        uses: actions/upload-artifact@v2
        with:
            name: KDoc Documentation Site
            path: app/build/dokka/html
